### ISSUE TITLE
JsonList的疑问

### ISSUE THREAD

**Issue by SherlockGougou** [kongzue/BaseJson#1]
如下这种数据，如何使用JsonMap和JsonList解析？
```
{
    "data": {
        "visible": true,
        "styleList": [
            {
                "targetPicStyle": "CG",
                "targetPicStyleDesc": "CG",
                "picUrl": "https://cs/data/diffusion/cg.jpg"
            },
            {
                "targetPicStyle": "anime",
                "targetPicStyleDesc": "anime",
                "picUrl": "https://cs/data/diffusion/anime.jpg"
            }
        ]
    }
}
```

**Comment by kongzue** [comment]
```java
JsonMap originData = new JsonMap("...");    //文本传入原始数据
String firstItemTargetPicStyle = originData.getJsonMap("data")
        .getList("styleList")
        .getJsonMap(0)
        .getString("targetPicStyle");
//firstItemTargetPicStyle只会是空值不会是空指针，上述代码永远不会报空指针，最多只会结果是空值
```

**Comment by SherlockGougou** [comment]
外层的数据我是用一个BaseResponse解析到的，类似：
```
class BaseResponse {
    public T data;
}
```
网络工具做了自动解析，泛型我传入JsonMap，但是无法获取内层data中的styleList

**Comment by SherlockGougou** [comment]
我现在是先将```data.get("styleList")```转换为json字符串，然后再解析为JsonList，这样是可以的。

**Comment by SherlockGougou** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/17920617/232976445-23d147c0-7a9c-450b-b148-8da48390529f.png">

**Comment by kongzue** [comment]
那其实跟我的BaseOkHttpV3也差不多，但是我做了个专门的JsonMap回调，会默认把结果转成 JsonMap，很好处理

**Comment by kongzue** [comment]
我自己的开发流程已经完全不去做Bean了，基本上所有数据都是直接存json内容，然后读取也是直接读成jsonMap/jsonList做解析，IO开销交给缓存层或MMKV去解决是完全ok的。BaseJson主要解决的是后端可能不规范或者犯蠢瞎修改字段引发的App崩溃问题。

**Comment by kongzue** [comment]
另外就是对于不需要处理但需要展示的jsonList是完全可以直接对接Adapter丢UI去渲染列表的，这就极大的节省了时间，提升开发效率

**Comment by SherlockGougou** [comment]
我也是这样想的，也是准备这样用的；Bean的存在完全有些多余；对于上面这个问题等以后有空我再改改网络封装那边，适配一下吧。

**Comment by kongzue** [comment]
除非有必要，不然我觉着开发效率肯定是第一位的，然后再考虑运行效率，说实话哪怕性能开销有点大，大不了异步线程+稍微转转圈也能接受，不出事稳定可靠顺手才是最重要的
